"""GitHub API access that degrades instead of exploding.

The card used to be generated by a script that raised on the first GraphQL
error it saw.  That made the whole workflow fail — and mail out a red build —
the moment the personal access token expired and Actions silently fell back
to the repository-scoped GITHUB_TOKEN, which is not allowed to read
stargazer counts on other repositories:

    FORBIDDEN … 'Resource not accessible by integration'

GraphQL reports that per field: the response still carries a perfectly good
`data` block with the inaccessible fields nulled out.  So every call here
keeps partial data, records a warning, and lets the caller fall back to a
REST endpoint or to yesterday's cached value.  Nothing in this module raises
for a missing metric; only a completely unusable token is fatal.
"""

from __future__ import annotations

import json
import time
from pathlib import Path

import requests

GRAPHQL_URL = "https://api.github.com/graphql"
REST_ROOT = "https://api.github.com"
TIMEOUT = 30

LOC_CACHE = Path("cache/loc_cache.json")
LEGACY_LOC_CACHE = Path("cache/loc_cache.txt")


class TokenUnusable(RuntimeError):
    """Raised when the token cannot even identify the user."""


class GitHubClient:
    """Thin wrapper over the GitHub REST and GraphQL APIs."""

    def __init__(self, token: str, login: str):
        self.login = login
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
                "User-Agent": f"{login}-profile-card",
            }
        )
        # Set once a FORBIDDEN is seen, so the caller can explain the cause
        # exactly once instead of per field.
        self.saw_forbidden = False

    # ── transport ────────────────────────────────────────────────────────

    def graphql(self, query: str, variables: dict) -> tuple[dict | None, list]:
        """Run a GraphQL query.  Returns (data, error_messages).

        Partial responses are normal here: `data` may be present alongside
        errors, with the forbidden fields set to null.
        """
        try:
            resp = self.session.post(
                GRAPHQL_URL,
                json={"query": query, "variables": variables},
                timeout=TIMEOUT,
            )
        except requests.RequestException as exc:
            return None, [f"request failed: {exc}"]

        if resp.status_code == 401:
            return None, ["401 unauthorized – the token is invalid or expired"]
        if resp.status_code != 200:
            return None, [f"HTTP {resp.status_code}: {resp.text[:200]}"]

        try:
            payload = resp.json()
        except ValueError:
            return None, ["response was not JSON"]

        messages = []
        for err in payload.get("errors") or []:
            if err.get("type") == "FORBIDDEN":
                self.saw_forbidden = True
            path = ".".join(str(p) for p in err.get("path", []))
            messages.append(f"{err.get('type', 'ERROR')} at {path or '?'}")

        return payload.get("data"), messages

    def rest(self, path: str, **params) -> tuple[int, object]:
        """Run a REST request.  Returns (status_code, parsed_body_or_None)."""
        try:
            resp = self.session.get(
                f"{REST_ROOT}{path}", params=params or None, timeout=TIMEOUT
            )
        except requests.RequestException:
            return 0, None
        if resp.status_code == 403:
            self.saw_forbidden = True
        try:
            return resp.status_code, resp.json()
        except ValueError:
            return resp.status_code, None

    # ── capability probe ─────────────────────────────────────────────────

    def probe(self) -> dict:
        """Describe what this token can actually do, for the job summary."""
        data, errors = self.graphql(
            """
            query($login: String!) {
              viewer { login }
              user(login: $login) {
                login
                repositories(first: 1, ownerAffiliations: [OWNER]) {
                  nodes { stargazerCount }
                }
              }
            }
            """,
            {"login": self.login},
        )
        if data is None:
            raise TokenUnusable("; ".join(errors) or "no data returned")

        viewer = (data.get("viewer") or {}).get("login")
        nodes = ((data.get("user") or {}).get("repositories") or {}).get("nodes") or []
        can_read_stars = bool(nodes) and nodes[0].get("stargazerCount") is not None
        return {
            "viewer": viewer,
            "personal_token": viewer is not None,
            "can_read_stars": can_read_stars,
            "errors": errors,
        }

    # ── repositories ─────────────────────────────────────────────────────

    def fetch_repositories(self) -> tuple[list, list]:
        """Return (repos, warnings).

        Each repo is a dict with slug, pushed_at, stars, forks and a
        language→bytes mapping.  Tries GraphQL first because it gets
        everything in one round trip, then falls back to REST for whatever
        the token was not allowed to see.
        """
        repos, warnings = self._repos_graphql()
        if repos is None:
            warnings.append("GraphQL repository listing unavailable; using REST")
            repos, rest_warnings = self._repos_rest()
            return repos, warnings + rest_warnings

        # GraphQL answered, but a repo-scoped token nulls out per-repo
        # counters.  Patch those in over REST rather than reporting zeros.
        if repos and all(r["stars"] is None for r in repos):
            warnings.append(
                "token cannot read star/fork counts over GraphQL; using REST"
            )
            self._patch_counts_from_rest(repos)

        missing_langs = [r for r in repos if not r["languages"]]
        if missing_langs and len(missing_langs) == len(repos):
            warnings.append("token cannot read language bytes over GraphQL; using REST")
            self._patch_languages_from_rest(missing_langs)

        return repos, warnings

    def _repos_graphql(self) -> tuple[list | None, list]:
        query = """
        query($login: String!, $cursor: String) {
          user(login: $login) {
            repositories(
              first: 50
              after: $cursor
              ownerAffiliations: [OWNER]
              isFork: false
              orderBy: { field: PUSHED_AT, direction: DESC }
            ) {
              totalCount
              pageInfo { endCursor hasNextPage }
              nodes {
                nameWithOwner
                pushedAt
                isPrivate
                stargazerCount
                forkCount
                languages(first: 12, orderBy: { field: SIZE, direction: DESC }) {
                  edges { size node { name } }
                }
              }
            }
          }
        }"""

        repos: list = []
        warnings: list = []
        cursor = None
        while True:
            data, errors = self.graphql(query, {"login": self.login, "cursor": cursor})
            warnings.extend(errors)
            if data is None:
                return None, warnings
            user = data.get("user")
            if not user:
                return None, warnings + [f"user {self.login} not visible to this token"]

            block = user.get("repositories") or {}
            for node in block.get("nodes") or []:
                if not node:
                    continue
                langs = {}
                for edge in ((node.get("languages") or {}).get("edges")) or []:
                    name = (edge.get("node") or {}).get("name")
                    if name:
                        langs[name] = edge.get("size", 0)
                repos.append(
                    {
                        "slug": node["nameWithOwner"],
                        "pushed_at": node.get("pushedAt") or "",
                        "private": bool(node.get("isPrivate")),
                        "stars": node.get("stargazerCount"),
                        "forks": node.get("forkCount"),
                        "languages": langs,
                    }
                )

            page = block.get("pageInfo") or {}
            if not page.get("hasNextPage"):
                break
            cursor = page.get("endCursor")

        return repos, warnings

    def _repos_rest(self) -> tuple[list, list]:
        """Public-repository fallback that works with any usable token."""
        repos: list = []
        warnings: list = []
        page = 1
        while page <= 10:
            status, body = self.rest(
                f"/users/{self.login}/repos",
                per_page=100,
                page=page,
                type="owner",
                sort="pushed",
            )
            if status != 200 or not isinstance(body, list):
                warnings.append(f"REST repository listing failed (HTTP {status})")
                break
            for item in body:
                if item.get("fork"):
                    continue
                repos.append(
                    {
                        "slug": item["full_name"],
                        "pushed_at": item.get("pushed_at") or "",
                        "private": bool(item.get("private")),
                        "stars": item.get("stargazers_count", 0),
                        "forks": item.get("forks_count", 0),
                        "languages": {},
                    }
                )
            if len(body) < 100:
                break
            page += 1

        self._patch_languages_from_rest(repos)
        return repos, warnings

    def _patch_counts_from_rest(self, repos: list) -> None:
        by_slug = {}
        page = 1
        while page <= 10:
            status, body = self.rest(
                f"/users/{self.login}/repos", per_page=100, page=page, type="owner"
            )
            if status != 200 or not isinstance(body, list):
                break
            for item in body:
                by_slug[item["full_name"]] = item
            if len(body) < 100:
                break
            page += 1

        for repo in repos:
            item = by_slug.get(repo["slug"])
            if item is None:
                continue
            repo["stars"] = item.get("stargazers_count", 0)
            repo["forks"] = item.get("forks_count", 0)

    def _patch_languages_from_rest(self, repos: list) -> None:
        for repo in repos:
            status, body = self.rest(f"/repos/{repo['slug']}/languages")
            if status == 200 and isinstance(body, dict):
                repo["languages"] = {k: int(v) for k, v in body.items()}

    # ── scalar metrics ───────────────────────────────────────────────────

    def fetch_followers(self) -> tuple[int | None, list]:
        data, errors = self.graphql(
            "query($login: String!) { user(login: $login) { followers { totalCount } } }",
            {"login": self.login},
        )
        followers = ((data or {}).get("user") or {}).get("followers")
        if followers and followers.get("totalCount") is not None:
            return followers["totalCount"], errors

        status, body = self.rest(f"/users/{self.login}")
        if status == 200 and isinstance(body, dict):
            return body.get("followers"), errors
        return None, errors + ["follower count unavailable"]

    def fetch_contributed(self) -> tuple[int | None, list]:
        data, errors = self.graphql(
            """
            query($login: String!) {
              user(login: $login) {
                repositoriesContributedTo(
                  first: 1
                  contributionTypes: [COMMIT, PULL_REQUEST, REPOSITORY]
                ) { totalCount }
              }
            }""",
            {"login": self.login},
        )
        block = ((data or {}).get("user") or {}).get("repositoriesContributedTo")
        if block and block.get("totalCount") is not None:
            return block["totalCount"], errors
        return None, errors + ["contributed-repo count unavailable"]

    def fetch_commit_total(self) -> tuple[int | None, list]:
        """All-time authored commits, via the commit search API."""
        try:
            resp = self.session.get(
                f"{REST_ROOT}/search/commits",
                params={"q": f"author:{self.login}", "per_page": 1},
                timeout=TIMEOUT,
            )
        except requests.RequestException as exc:
            return None, [f"commit search failed: {exc}"]

        if resp.status_code == 403:
            self.saw_forbidden = True
            return None, ["commit search forbidden for this token"]
        if resp.status_code != 200:
            return None, [f"commit search returned HTTP {resp.status_code}"]
        try:
            return resp.json().get("total_count"), []
        except ValueError:
            return None, ["commit search response was not JSON"]

    def fetch_contribution_calendar(self) -> tuple[list, int | None, list]:
        """Return (daily_counts, total, warnings) for the trailing year."""
        data, errors = self.graphql(
            """
            query($login: String!) {
              user(login: $login) {
                contributionsCollection {
                  contributionCalendar {
                    totalContributions
                    weeks { contributionDays { date contributionCount } }
                  }
                }
              }
            }""",
            {"login": self.login},
        )
        calendar = (
            ((data or {}).get("user") or {}).get("contributionsCollection") or {}
        ).get("contributionCalendar")
        if not calendar:
            return [], None, errors + ["contribution calendar unavailable"]

        days = []
        for week in calendar.get("weeks") or []:
            for day in week.get("contributionDays") or []:
                days.append((day.get("date", ""), day.get("contributionCount", 0)))
        days.sort(key=lambda pair: pair[0])
        return days, calendar.get("totalContributions"), errors

    # ── lines of code ────────────────────────────────────────────────────

    def fetch_loc(self, repos: list) -> tuple[int | None, int | None, list]:
        """Sum additions/deletions this user authored across *repos*.

        Results are cached per repository and only refetched when the repo
        has been pushed to since the cached reading.  The previous
        implementation cached by slug alone, so once a repository was seen
        its line count was frozen forever and the card slowly went stale.
        """
        cache = _load_loc_cache()
        warnings: list = []
        # Start from the existing cache rather than an empty dict.  A run
        # whose token can only see part of the account would otherwise prune
        # every repository it could not list, and the headline line count
        # would lurch downwards for reasons that have nothing to do with the
        # code that was actually written.
        updated: dict = dict(cache)
        failures = 0

        for repo in repos:
            slug = repo["slug"]
            pushed = repo.get("pushed_at") or ""
            entry = cache.get(slug)
            if entry and entry.get("pushed_at") == pushed:
                continue  # the cached reading is still current

            result = self._contributor_totals(slug)
            if result is None:
                failures += 1  # keep whatever the cache already held
                continue
            adds, dels = result
            updated[slug] = {"a": adds, "d": dels, "pushed_at": pushed}

        if failures:
            warnings.append(
                f"line-count statistics unavailable for {failures} repositor"
                f"{'y' if failures == 1 else 'ies'}"
            )

        _save_loc_cache(updated)
        if not updated:
            return None, None, warnings

        total_adds = sum(e["a"] for e in updated.values())
        total_dels = sum(e["d"] for e in updated.values())
        return total_adds, total_dels, warnings

    def _contributor_totals(self, slug: str) -> tuple[int, int] | None:
        """Additions/deletions authored by this user in one repository."""
        for attempt in range(4):
            status, body = self.rest(f"/repos/{slug}/stats/contributors")
            if status == 202:
                # GitHub is computing the statistics; back off and retry.
                time.sleep(3 * (attempt + 1))
                continue
            if status != 200 or not isinstance(body, list):
                return None
            adds = dels = 0
            for contributor in body:
                author = (contributor.get("author") or {}).get("login") or ""
                if author.lower() != self.login.lower():
                    continue
                for week in contributor.get("weeks") or []:
                    adds += week.get("a", 0)
                    dels += week.get("d", 0)
            return adds, dels
        return None


# ── LOC cache persistence ────────────────────────────────────────────────


def _load_loc_cache() -> dict:
    if LOC_CACHE.exists():
        try:
            return json.loads(LOC_CACHE.read_text())
        except (ValueError, OSError):
            return {}
    # Migrate the original "slug adds dels" text format.  No pushed_at is
    # recorded, which forces exactly one refresh per repository.
    if LEGACY_LOC_CACHE.exists():
        migrated = {}
        for line in LEGACY_LOC_CACHE.read_text().splitlines():
            parts = line.split()
            if len(parts) == 3 and parts[1].isdigit() and parts[2].isdigit():
                migrated[parts[0]] = {
                    "a": int(parts[1]),
                    "d": int(parts[2]),
                    "pushed_at": "",
                }
        return migrated
    return {}


def _save_loc_cache(entries: dict) -> None:
    LOC_CACHE.parent.mkdir(parents=True, exist_ok=True)
    LOC_CACHE.write_text(json.dumps(entries, indent=2, sort_keys=True) + "\n")
